### ISSUE TITLE
「任务分配」4. Views

### ISSUE THREAD

**Issue by ApolloZhu** [ApolloZhu/Developing-iOS-10-Apps-with-Swift#14]
|字幕序号|翻译人员|状态|校对人员|状态|
|--|--|--|--|--|
|1-110|@ApolloZhu|已完成||待认领|
|105-128|@CrowsStriker|已完成||待认领|
|129-500|@ApolloZhu|已完成||待认领|
|501-632|@CrowsStriker|已完成||待认领|
|633-900|@VoiceBeer|已完成||待认领|
|901-1399|@kingkangyu|已完成||待认领|
|1363-1399|@VoiceBeer|已完成||待认领|
|1400-1895|@ApolloZhu|已完成||待认领|

**Comment by CrowsStriker** [comment]
所以这个翻译还在进行中吗？

**Comment by ApolloZhu** [comment]
至少我还在，不过任务量大，还是希望能有人帮忙

**Comment by CrowsStriker** [comment]
那我现在想加入翻译要怎么弄？不是很熟悉github

**Comment by ApolloZhu** [comment]
谢谢，具体步骤可以参考 [这里](https://github.com/ApolloZhu/Developing-iOS-10-Apps-with-Swift/blob/master/CONTRIBUTING.md)。您考虑翻译 501-900 如何？

**Comment by CrowsStriker** [comment]
👌好的发自我的iPhone------------------ 原始邮件 ------------------发件人: 朱智语  <notifications@github.com>发送时间: 2017年7月16日 00:02收件人: ApolloZhu/Developing-iOS-10-Apps-with-Swift <Developing-iOS-10-Apps-with-Swift@noreply.github.com>抄送: Crows <crowsstriker@gmail.com>, Comment <comment@noreply.github.com>主题: 回复：[ApolloZhu/Developing-iOS-10-Apps-with-Swift] 「任务分配」4. Views (#14)谢谢，具体步骤可以参考 这里。您考虑翻译 501-900 如何？

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ApolloZhu/Developing-iOS-10-Apps-with-Swift","title":"ApolloZhu/Developing-iOS-10-Apps-with-Swift","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/ApolloZhu/Developing-iOS-10-Apps-with-Swift"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ApolloZhu in #14: 谢谢，具体步骤可以参考 [这里](https://github.com/ApolloZhu/Developing-iOS-10-Apps-with-Swift/blob/master/CONTRIBUTING.md)。您考虑翻译 501-900 如何？"}],"action":{"name":"View Issue","url":"https://github.com/ApolloZhu/Developing-iOS-10-Apps-with-Swift/issues/14#issuecomment-315543860"}}}

**Comment by CrowsStriker** [comment]
我刚刚pull request了，你看看对了吗-。-

**Comment by ApolloZhu** [comment]
稍微有几个小问题，都是因为我的具体步骤没写清楚导致的，非常抱歉，之后我会再修改。
1. 翻译是翻译 subtitles 文件夹里的字幕，还请您转移一下翻译（不能够直接复制文件， 因为英文提前被我合并成了一行）
2. 希望您能够翻译分配的“行数”, 这里的行数不是指文件里的行数，因为那个会因为翻译的内容增加改变，所以这次希望您翻译的是 [这个部分](https://github.com/ApolloZhu/Developing-iOS-10-Apps-with-Swift/blob/master/subtitles/4.%20Views.srt#L2005-L3604)。不过希望您保留第四集 105-128（我正好只翻译到了 101，我就不翻译那部分了）。如果您觉得有点多，可以给我说，我可以重新分下段。
3. 非常感谢您能够翻译更多的内容，现在人不多（虽然不一定多得起来），但是为了避免其他人也翻译同样的内容， 还请您提前说一下 (比如这次的第五集 4-42，于是顺便我就给您分配了 [第五集 4-99](https://github.com/ApolloZhu/Developing-iOS-10-Apps-with-Swift/issues/19))
4. 全部翻译完之后提交 pull request 会出现在 [这里](https://github.com/ApolloZhu/Developing-iOS-10-Apps-with-Swift/pulls)。您可以在转移完目前的翻译之后提交一次 pull request 试一下，步骤可以参考 https://help.github.com/articles/creating-a-pull-request-from-a-fork/

**Comment by kingkangyu** [comment]
@ApolloZhu 901-1399我可以翻译一下

**Comment by ApolloZhu** [comment]
好的，麻烦您了

> P.S. 刚才有一瞬间迷糊了，最上面的信息写错了，已更正。（希望没有人看到，看来我是撑不住了，先睡了）

**Comment by CrowsStriker** [comment]
我还是有点懵，我是先folk了文件，然后在我的直接打开sub文件，然后点edit进行编辑，最后翻译了部分，我就点了pull request，然后merge，是这样操作吗？

**Comment by ApolloZhu** [comment]
## 原来是这样啊，我一般是 clone 到本地翻译的。如果您是在网页上操作的话，直接 commit 就可以了
![image](https://user-images.githubusercontent.com/10842684/28256429-765b2444-6a90-11e7-9a27-335ce5e80e07.png)
## 把全部分配的翻译完了之后，点这里的 New Pull Request
![image](https://user-images.githubusercontent.com/10842684/28256456-b1fb26a2-6a90-11e7-8d5b-aedad91abe98.png)

**Comment by CrowsStriker** [comment]
好吧，我是点了create a new bunch....

**Comment by ApolloZhu** [comment]
@CrowsStriker 你稍微停一下，我给你改一部分你再继续

**Comment by ApolloZhu** [comment]
@CrowsStriker 你合并一下 CrowsStriker#3，根据里面提出的继续翻译

**Comment by CrowsStriker** [comment]
还是不熟悉这个GitHub，我明天白天看看

**Comment by ApolloZhu** [comment]
好

**Comment by ApolloZhu** [comment]
@CrowsStriker 你看下 CrowsStriker#3

**Comment by CrowsStriker** [comment]
抱歉出去旅游了一段时间-。-明天开始继续翻译

**Comment by CrowsStriker** [comment]
2017-8-17 3：53

translate at 632;
problem at  571 - 574；580；592 - 594；

**Comment by ApolloZhu** [comment]
鉴于 @VoiceBeer 已经完成了第四集的翻译
请 @CrowsStriker 和 @kingkangyu 两位把目前的翻译直接提 pull request 过来就行了
请 @VoiceBeer 只保留第四集 633-900 和 1363-1399 的翻译也是正常的 pull request
我会尽快地完成简单校对然后合并

**Comment by kingkangyu** [comment]
好的 我回家后再简单校对一下，今晚提交一下

**Comment by VoiceBeer** [comment]
@ApolloZhu pull啦

**Comment by kingkangyu** [comment]
@ApolloZhu 翻译已经pull了

**Comment by CrowsStriker** [comment]
pull request了，但不知道对了没-。-
