### ISSUE TITLE
「任务分配」3. More Swift and the Foundation Framework

### ISSUE THREAD

**Issue by ApolloZhu** [ApolloZhu/Developing-iOS-10-Apps-with-Swift#6]
|字幕序号|翻译人员|状态|校对人员|状态|
|--|--|--|--|--|
|1-497|@LiulietLee|完成||待认领|
|498-800|@superk589|完成||待认领|
|801-1197|@superk589|完成||待认领|
|1198-1610|@superk589|完成||待认领|

**Comment by ApolloZhu** [comment]
@Sat-ice 第一段没问题吧

**Comment by Sat-ice** [comment]
@ApolloZhu 👌

**Comment by ApolloZhu** [comment]
好，谢谢了

**Comment by superk589** [comment]
申请翻译498-800

**Comment by ApolloZhu** [comment]
好，谢谢

**Comment by superk589** [comment]
@ApolloZhu 确认收到

**Comment by superk589** [comment]
继续申请 801-1197

**Comment by ApolloZhu** [comment]
好，谢谢

**Comment by superk589** [comment]
@ApolloZhu 确认收到

**Comment by superk589** [comment]
### 原文
929
00:50:13,013 --> 00:50:15,713
You can take it outside of the curly braces. Cuz you already

930
00:50:15,782 --> 00:50:17,449
got the curly braces, and that's why they do it.

### 问题
这里有问题...听不太懂
929 英文字幕有误 说的实际上是
You can take it outside, to put the curly braces ... (听不清这里是怎么连接的?) you really

然后 930 这句要表达啥有点不明所以 也许英文字幕也有问题?
got the curly braces, and that's why they do it.

**Comment by ApolloZhu** [comment]
估计是说错了吧，想办法蹭过去了。我目前能想到的替代方法是这样的，你可以参考一下
```
929
00:50:13,013 --> 00:50:15,713
You can take it outside, just put the curly braces. Cuz you already
你可以把闭包从小括号中提出来，只留下大括号这部分

930
00:50:15,782 --> 00:50:17,449
got the curly braces, and that's why they do it.
因为已经有大括号扩起来了，所以语法允许

931
XXX（没打开字幕文件，你自己补一下）
XXX
你可以省略周围的小括号
```

注：Cuz 是 because，这个部分没问题

**Comment by superk589** [comment]
申请 1198-1610
这次也许时间会长一点 最晚能否放宽至5月20日

**Comment by ApolloZhu** [comment]
好，谢谢

**Comment by ApolloZhu** [comment]
@Sat-ice 翻译得怎么样了？能在 5/20 之前完成吗？
